/*******************************************************************************
 * Copyright (C) 2019-2025 MarbleBag
 * Copyright (C) 2026 Shuro
 *
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the Free
 * Software Foundation, version 3.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 *******************************************************************************/

'use strict';

import "/module/JQueryExtensions"
import * as Databinding from '/module/Databinding'
import * as Config from '/module/Config'
import * as Locale from '/module/Locale'
import * as Style from '/module/Style'
import * as Dialog from '/module/Dialog'
import * as NavControl from '/module/MenuNavigationComponent'
import * as ProfileControl from '/module/ProfileControl'

//import '/module/WebComponents'

// initialize global variables
window.gobConfig = new Config.GobchatConfig()
window.gobConfig.loadFromLocalStore(true)

window.gobLocale = new Locale.LocaleManager()

window.gobStyles = new Style.StyleLoader("..")
await gobStyles.initialize()

// Coloris (color picker) global defaults. Individual inputs are enrolled by
// Components.makeColorSelector via the "[data-coloris]" attribute, so this only needs
// to run once. themeMode is kept in sync with the active light/dark theme below.
if (typeof Coloris !== "undefined") {
    Coloris({
        el: "[data-coloris]",
        wrap: true,
        alpha: true,
        format: "auto",
        formatToggle: false,
        clearButton: true,
        focusInput: false,
        themeMode: "dark",
    })
}

// The new settings design carries its dark/light palette on the root element's
// data-theme attribute; mirror the active FFXIV theme (…Dark / …Light) onto it (and onto Coloris).
function applyThemeMode(themeName: string | null | undefined): void {
    const mode = /light/i.test(themeName ?? "") ? "light" : "dark"
    // Put it on <html> so the design tokens inherit everywhere, including modal <dialog>s
    // (which render in the top layer but still inherit custom properties from their ancestors).
    document.documentElement.setAttribute("data-theme", mode)
    if (typeof Coloris !== "undefined") Coloris({ themeMode: mode })
}
applyThemeMode(gobConfig.get("style.theme"))

{
    const configBinding = new Databinding.BindingContext(window.opener.gobConfig)
    configBinding.bindCallback("behaviour.frame.chat.position.x", value => gobConfig.set("behaviour.frame.chat.position.x", value))
    configBinding.bindCallback("behaviour.frame.chat.position.y", value => gobConfig.set("behaviour.frame.chat.position.y", value))
    configBinding.bindCallback("behaviour.frame.chat.size.width", value => gobConfig.set("behaviour.frame.chat.size.width", value))
    configBinding.bindCallback("behaviour.frame.chat.size.height", value => gobConfig.set("behaviour.frame.chat.size.height", value))
    configBinding.loadBindings()

    $(window).on("beforeunload", function () {
        configBinding.clearBindings()
    })
}


const binding = new Databinding.BindingContext(gobConfig)

// update all text on language change
gobLocale.setLocale(gobConfig.get("behaviour.language"))
binding.bindCallback("behaviour.language", async (value) => {
    gobLocale.setLocale(value)
    gobLocale.updateElement($(document))
    // The Coloris "Clear" button label is not a DOM node we can tag with data-gob-locale-text,
    // so re-issue it here (Coloris merges options) whenever the language changes.
    if (typeof Coloris !== "undefined") {
        try {
            Coloris({ clearLabel: await gobLocale.get("config.colorpicker.clear", value) })
        } catch (e1) {
            console.error(e1)
        }
    }
})

binding.bindCallback("style.theme", async (value) => {
    applyThemeMode(value)
    try {
        await gobStyles.activateStyles(value, $("#gob_autogenerated_stylesheet"), "before")
    } catch (e1) {
        console.error(e1)
        await gobStyles.activateStyles()
    }
})

binding.bindCallback("style", (value) => {
    try {
        Style.StyleBuilder.generateAndSetCssRules("gob_autogenerated_stylesheet")
    } catch (e1) {
        console.error(e1)
    }
})

const selProfile = $("#cp-main_profile-select")
selProfile.on("change", async (event) => {
    const profileId = event.target.value as string
    // The switch (warn-on-unsaved, discard, apply-live) is shared with the Profiles page; on a
    // cancelled or aborted switch, snap the dropdown back to the still-active profile.
    const switched = await ProfileControl.requestProfileSwitch(profileId)
    if (!switched)
        selProfile.val(gobConfig.activeProfileId ?? "")
})

function populateProfileSelection() {
    selProfile.empty()

    gobConfig.profileIds
        .map(profileId => {
            var profile = gobConfig.getProfile(profileId) as Config.ConfigProfile
            return { name: profile.profileName, id: profileId }
        })
        .sort((a, b) => {
            if (a.name < b.name)
                return -1;
            if (a.name > b.name)
                return 1;
            return 0;
        })
        .forEach(e => {
            selProfile.append(new Option(e.name, e.id))
        })

    selProfile.val(gobConfig.activeProfileId)
}

gobConfig.addProfileEventListener((event) => {
    if (event.action === "active") {
        selProfile.val(event.newProfileId)
    } else {
        populateProfileSelection()
    }
})

gobConfig.addPropertyEventListener("profile.name", () => {
    const profileId = selProfile.val()
    populateProfileSelection()
    selProfile.val(profileId) // restore old selection
})

populateProfileSelection()

const mutationObserver = new window.MutationObserver((mutations, observer) => {
    for (const mutation of mutations) {
        let updateElement = false

        if (mutation.type === 'attributes')
            updateElement = mutation.attributeName === Locale.HtmlAttribute.TextId || mutation.attributeName === Locale.HtmlAttribute.TooltipId

        if (updateElement && mutation.target instanceof HTMLElement) {
            const target = mutation.target
            if (target.getAttribute(Locale.HtmlAttribute.ActiveLocale) !== gobLocale.locale)
                gobLocale.updateElement(target)
        }
            
    }
})

mutationObserver.observe(document.body, { childList: false, subtree: true, attributes: true })

// The Debug page is developer-only; drop its nav entry in Release builds before the panels are built
// so its page is never fetched.
if (!(await GobchatAPI.isDebugBuild()))
    $(".gob-config-navigation_entry[data-gob-nav-target='config_debug.html']").remove()

await NavControl.makeControl($(".gob-config-navigation"))

binding.loadBindings()

// initialize main buttons

// The single Save button now saves AND closes the settings window.
$("#cp-main_save-config").on("click", function () {
    ProfileControl.logUnsavedChanges("Settings save requested - changes being written")
    window.gobConfig.saveToLocalStore()
    window.saveConfig()
    window.close()
})

// The disk button beside Save persists the config but keeps the settings window open.
$("#cp-main_apply-config").on("click", function () {
    ProfileControl.logUnsavedChanges("Settings apply requested - changes being written")
    window.gobConfig.saveToLocalStore()
    window.saveConfig()
})

const cancelConfig = async function () {
    // Only nag when there's something to lose: with no unsaved edits, close straight away.
    if (!ProfileControl.hasUnsavedChanges()) {
        window.close()
        return
    }
    ProfileControl.logUnsavedChanges("Settings close/cancel requested - unsaved changes will be discarded")
    const result = await Dialog.showConfirmationDialog({ dialogText: "config.main.nav.cancel.dialog" })
    if (result)
        window.close()
}

$("#cp-main_cancel-config").on("click", cancelConfig)

// The title-bar close button discards unsaved changes (same as Cancel).
$("#cp-main_titlebar-close").on("click", cancelConfig)

// The title-bar minimize button sends the (now taskbar-listed) settings window to the taskbar.
$("#cp-main_titlebar-minimize").on("click", function () {
    GobchatAPI.minimizeSettings()
})

// The title-bar pin toggles the settings window's always-on-top state (off by default).
let settingsPinned = false
$("#cp-main_titlebar-pin").on("click", function () {
    settingsPinned = !settingsPinned
    $(this).toggleClass("is-active", settingsPinned)
    GobchatAPI.setSettingsAlwaysOnTop(settingsPinned)
})

$("#cp-main_close-gobchat").on("click", async function () {
    // With unsaved changes, warn about losing them first, then confirm the exit itself (two prompts).
    if (ProfileControl.hasUnsavedChanges()) {
        ProfileControl.logUnsavedChanges("Exit GobchatEx requested - unsaved changes will be discarded")
        const discard = await Dialog.showConfirmationDialog({ dialogText: "config.main.nav.cancel.dialog" })
        if (!discard)
            return
    }
    const result = await Dialog.showConfirmationDialog({ dialogText: "config.main.nav.closegobchat.dialog" })
    if (result) {
        window.close()
        GobchatAPI.closeGobchat()
    }
})

// Everything above has built and themed the page. Reveal the (until-now hidden) settings window so it
// appears already rendered, with no empty-frame flash. The host also has a watchdog + failed-load
// fallback, so a failure here can't leave the window invisible.
try {
    await GobchatAPI.revealSettings()
} catch (e) {
    console.error("Failed to signal settings window reveal", e)
}
