/*******************************************************************************
 * Copyright (C) 2019-2025 MarbleBag
 * Copyright (C) 2026 Shuro
 *
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the Free
 * Software Foundation, version 3.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 *******************************************************************************/

// compiler doesn't recognize globals.d.ts for this file

'use strict'

import * as Databinding from './modules/Databinding.js'
import * as Config from './modules/Config.js'
import * as Locale from './modules/Locale.js'
import * as Style from './modules/Style.js'
import * as Chat from './modules/Chat.js'

// The host bridge only forwards console.* output to the log, not engine-level uncaught errors
// or rejected promises. Forward those explicitly so frontend failures show up in
// gobchatex_debug.log instead of dying silently in the WebView2.
window.addEventListener('error', (e) => {
    const err = (e as ErrorEvent).error
    console.error(`[uncaught] ${(e as ErrorEvent).message} @ ${(e as ErrorEvent).filename}:${(e as ErrorEvent).lineno}:${(e as ErrorEvent).colno}`, err && err.stack ? err.stack : '')
})
window.addEventListener('unhandledrejection', (e) => {
    const reason = (e as PromiseRejectionEvent).reason
    console.error(`[unhandledrejection] ${reason && reason.stack ? reason.stack : reason}`)
})

// Indicate that window resizing is possible
document.addEventListener("OverlayStateUpdate", function (event: OverlayStateUpdateEvent) {
    if (!event.detail.isLocked)
        document.documentElement.classList.add("gob-document--resize");
    else
        document.documentElement.classList.remove("gob-document--resize");
} as EventListener);

// initialize global variables
jQuery(async function ($) {
    window.gobConfig = new Config.GobchatConfig(true)
    await gobConfig.loadConfig()
    
    window.gobLocale = new Locale.LocaleManager()

    window.gobStyles = new Style.StyleLoader(".")
    await gobStyles.initialize()
 
    window.gobChatManager = new Chat.ChatControl()

    $("#gob_toggle_search").on("click", () => gobChatManager.toggleSearch())

    const binding = new Databinding.BindingContext(gobConfig)
    binding.bindCallback("behaviour.language", (value) => {
        gobLocale.setLocale(value)
        gobLocale.updateElement($(document))
    })

    binding.bindCallback("style.theme", async (value) => {
        try {
            await gobStyles.activateStyles(value, $("#gob_autogenerated_stylesheet"), "before")
        } catch (e1) {
            console.error(e1)
            await gobStyles.activateStyles()
        }
    })

    binding.bindCallback("style", (value) => {
        try {
            Style.StyleBuilder.generateAndSetCssRules("gob_autogenerated_stylesheet")
        } catch (e1) {
            console.error(e1)
        }
    })

    binding.loadBindings()
    
    gobChatManager.control($(`.${Chat.CssClass.Chat}`))
    gobChatManager.hideSearch()

    GobchatAPI.setUIReady(true)
});

// feature - open config
jQuery(function ($) {
    const localStorageKey = "gobchat-config-open"

    // A fresh page load means no config popup is associated with this overlay anymore. A leftover
    // "open" flag (e.g. from a popup whose close was never detected) would otherwise lock the user
    // out of settings permanently, so always clear it on load.
    window.localStorage.removeItem(localStorageKey)

    async function openGobchatConfig() {
        console.info("openGobchatConfig: requested")
        const isConfigOpen = window.localStorage.getItem(localStorageKey) || "false"

        if (isConfigOpen === "true") {
            console.info("openGobchatConfig: aborted, a settings window is already flagged as open")
            return
        }

        window.localStorage.setItem(localStorageKey, "true")

        try {
            gobConfig.saveToLocalStore()

            const bounds = await GobchatAPI.getScreenDimensions()
            console.info(`openGobchatConfig: screen dimensions = ${JSON.stringify(bounds)}`)
            const screenWidth = bounds.Item1
            const screenHeight = bounds.Item2

            const dialogWidth = screenWidth / 2
            const dialogHeight = screenHeight / 2

            const handle = window.open("config/config.html", 'Settings', `width=${dialogWidth},height=${dialogHeight}`)
            if (handle === null) {
                console.error(`openGobchatConfig: window.open returned null (requested ${dialogWidth}x${dialogHeight}), settings popup did not open`)
                window.localStorage.removeItem(localStorageKey)
                return
            }

            handle.saveConfig = function () {
                gobConfig.loadFromLocalStore()
            }

            handle.focus()
            console.info("openGobchatConfig: settings popup opened")

            const timer = setInterval(function () {
                if (handle.closed) {
                    clearInterval(timer);
                    window.localStorage.removeItem(localStorageKey)
                }
            }, 1000);
        } catch (e) {
            console.error(`openGobchatConfig: failed to open settings`, (e as any)?.stack ?? e)
            window.localStorage.removeItem(localStorageKey)
        }
    }

    $("#gob_show_config").on("click", openGobchatConfig)
    window.openGobConfig = openGobchatConfig
})